"use client";

import { use, useState, useEffect } from "react";
import Link from "next/link";
import { AppShell } from "@/components/ui/AppShell";
import { ProgressRing } from "@/components/ui/ProgressRing";
import { QuizCard } from "@/components/ui/QuizCard";
import { studentApi, type AttemptDetail } from "@/lib/edsynapseApi";
import { Trophy, ArrowLeft, Download, Printer, CheckCircle2, XCircle } from "lucide-react";

export default function AttemptReportPage({
  params,
}: {
  params: Promise<{ code: string; attemptId: string }>;
}) {
  const { code, attemptId } = use(params);

  const [detail, setDetail] = useState<AttemptDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    studentApi
      .getAttempt(attemptId)
      .then(setDetail)
      .catch((e) => setError(e instanceof Error ? e.message : "Couldn't load this report."))
      .finally(() => setLoading(false));
  }, [attemptId]);

  const pct = detail && detail.total > 0 ? Math.round((detail.score / detail.total) * 100) : 0;

  // Save the report as a plain-text file the student can keep.
  const downloadReport = () => {
    if (!detail) return;
    const lines = [
      "=========================================",
      "          EDSYNAPSE GRADE REPORT",
      "=========================================",
      `Course Code: ${code}`,
      `Topic: ${detail.topic}`,
      `Score: ${pct}% (${detail.score}/${detail.total} correct)`,
      `Date: ${new Date(detail.created_at).toLocaleString()}`,
      "",
      "QUESTION BREAKDOWN:",
      ...detail.review.map((r, i) => {
        const verdict = r.correct === null ? "REVIEW" : r.correct ? "CORRECT" : "INCORRECT";
        return [
          `${i + 1}. [${verdict}] ${r.prompt}`,
          `   Your Answer: ${r.studentResponse || "—"}`,
          `   Correct Answer: ${r.correctAnswer || "—"}`,
          `   Why: ${r.rationale}`,
          "",
        ].join("\n");
      }),
      "Generated by EdSynapse AI Tutor.",
      "=========================================",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `edsynapse_${code}_attempt_${detail.id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <AppShell role="student">
        <div className="max-w-4xl mx-auto py-24 flex flex-col items-center justify-center gap-3 text-center">
          <div className="w-9 h-9 animate-spin rounded-full border-2 border-primary/20 border-t-primary" />
          <p className="text-xs font-semibold text-muted-foreground">Loading your report…</p>
        </div>
      </AppShell>
    );
  }

  if (error || !detail) {
    return (
      <AppShell role="student">
        <div className="max-w-2xl mx-auto py-24 text-center space-y-3">
          <h1 className="text-xl font-bold text-foreground font-display">Report unavailable</h1>
          <p className="text-sm text-muted-foreground">
            {error || "This report wasn't found."}
          </p>
          <Link
            href={`/student/class/${code}/assessment`}
            className="inline-flex items-center gap-2 px-5 py-3 bg-primary text-white rounded-2xl text-sm font-bold hover:bg-primary/95 transition-all"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Go to Assessments</span>
          </Link>
        </div>
      </AppShell>
    );
  }

  const passed = pct >= 60;

  return (
    <AppShell role="student">
      <div className="max-w-4xl mx-auto space-y-8 print:p-0 print:max-w-full">
        {/* Header */}
        <div className="text-center space-y-4 print:hidden edsynapse-stagger">
          <div className="inline-flex p-4 rounded-3xl bg-amber-500/10 text-amber-500 border border-amber-500/20">
            <Trophy className="w-12 h-12" />
          </div>
          <div className="space-y-2">
            <h1 className="text-3xl font-black text-foreground font-display tracking-tight">Assessment Report</h1>
            <p className="text-sm text-muted-foreground max-w-md mx-auto">
              How you did on <span className="font-bold">{detail.topic}</span> ·{" "}
              {new Date(detail.created_at).toLocaleDateString(undefined, {
                month: "short",
                day: "numeric",
                year: "numeric",
              })}
            </p>
          </div>
        </div>

        {/* Score / overview */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-stretch">
          <div className="liquid-panel rounded-3xl p-6 flex flex-col items-center justify-center text-center gap-4">
            <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
              Final Assessment Score
            </span>
            <ProgressRing value={pct} size={130} strokeWidth={10} textClassName="text-2xl font-black text-primary" />
            <p className="text-xs font-semibold text-muted-foreground">
              {detail.score} of {detail.total} questions correct
            </p>
          </div>

          <div className="liquid-panel rounded-3xl p-6 flex flex-col justify-center gap-4">
            <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Result</span>
            <div className="flex items-center gap-3">
              <div
                className={`flex w-12 h-12 shrink-0 items-center justify-center rounded-2xl border ${
                  passed
                    ? "bg-emerald-500/10 text-emerald-600 border-emerald-500/20"
                    : "bg-amber-500/10 text-amber-600 border-amber-500/20"
                }`}
              >
                {passed ? <CheckCircle2 className="w-6 h-6" /> : <XCircle className="w-6 h-6" />}
              </div>
              <div>
                <h3 className="text-lg font-bold text-foreground font-display">{passed ? "Passed" : "Keep practicing"}</h3>
                <p className="text-xs text-muted-foreground">Topic: {detail.topic}</p>
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="liquid-panel rounded-3xl p-6 flex flex-col justify-between gap-6 print:hidden">
            <div className="space-y-1.5">
              <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Action Center</span>
              <h3 className="text-sm font-bold text-foreground font-display">Save or Print Report</h3>
              <p className="text-xs text-muted-foreground">Export your summary and question breakdowns.</p>
            </div>
            <div className="space-y-2">
              <button
                type="button"
                onClick={downloadReport}
                className="w-full flex items-center justify-center gap-2 py-3 bg-primary text-white rounded-2xl text-xs font-bold hover:bg-primary/95 transition-all shadow-lg shadow-primary/20 active:scale-[0.98]"
              >
                <Download className="w-4 h-4" />
                <span>Download Report</span>
              </button>
              <button
                type="button"
                onClick={() => window.print()}
                className="w-full flex items-center justify-center gap-2 py-3 bg-white/60 hover:bg-white text-foreground rounded-2xl text-xs font-bold border border-primary/10 transition-all active:scale-[0.98]"
              >
                <Printer className="w-4 h-4" />
                <span>Print Grade Slip</span>
              </button>
            </div>
          </div>
        </div>

        {/* Question-by-question breakdown */}
        <div className="space-y-6">
          <div className="flex items-center justify-between border-b border-white/30 pb-2">
            <h2 className="text-sm font-bold text-foreground uppercase tracking-wider font-display">
              Question-by-Question Breakdown
            </h2>
            <span className="text-xs text-muted-foreground font-semibold">
              {detail.review.length} questions reviewed
            </span>
          </div>

          <div className="space-y-4">
            {detail.review.map((r, idx) => (
              <QuizCard
                key={r.question_id}
                index={idx}
                question={r.prompt}
                type={r.type}
                options={r.type === "mcq" ? r.options : undefined}
                selectedAnswer={
                  r.type === "mcq"
                    ? r.selectedIndex >= 0
                      ? String(r.selectedIndex)
                      : ""
                    : r.studentResponse
                }
                correctAnswer={r.type === "mcq" ? String(r.correctIndex) : r.correctAnswer}
                onSelectAnswer={() => {}}
                showResults={true}
                explanation={r.rationale}
              />
            ))}
          </div>
        </div>

        {/* Footer nav */}
        <div className="flex items-center justify-between pt-4 print:hidden">
          <Link
            href={`/student/class/${code}/assessment`}
            className="flex items-center gap-2 px-4 py-3 rounded-2xl text-sm font-semibold text-muted-foreground hover:bg-white/40 transition-all border border-transparent hover:border-white/50"
          >
            <ArrowLeft className="w-4 h-4" strokeWidth={2} />
            <span>All Attempts</span>
          </Link>
        </div>
      </div>
    </AppShell>
  );
}
